rewrite logic for improved readibility
jamiealquiza/sadtomleditor pull request #4
Opened 2019-02-12 12:19 UTC by LeoCavaille

2019-02-12 14:17 UTC, marc-szalkiewicz-dd requested changes

2019-02-12 14:17 UTC, marc-szalkiewicz-dd commented on main.pl
> +my $infile = $ARGV[0];
should we consider upgrading to perl 6?

2019-02-12 14:21 UTC, benjaminws approved these changes
💅

2019-02-12 15:06 UTC, jamiealquiza commented
Closing in favor of this this re-rewrite for improved terseness and not-being-perl:

```awk
awk 'BEGIN {RS="[[";FS="\n";};{if ($0 ~ARGV[2]) for (i = 1; i <= NF; i++) { printf "#%s\n", $i; } else {print} }'
```

2019-02-12 15:09 UTC, jamiealquiza commented on main.pl
> +my $infile = $ARGV[0];
You mean Ruby?

2019-06-07 14:21 UTC, LeoCavaille commented
TOML was replaced by YAML closing this PR

2019-12-20 10:27 UTC, closed without merging